port: /dev/ttyDXL

joint_order: [turret_rot, turret_ext, turret_tilt, turret_pinch]

sleep_positions: [-3.14, 1.57, 0, 0]

joint_state_publisher:
  update_rate: 30
  publish_states: true
  topic_name: joint_states

groups:
  turret_group: [turret_rot, turret_ext, turret_tilt]
  pinch_group: [turret_pinch]

motors:
  turret_rot:
    ID: 19
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  turret_ext:
    ID: 20
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  turret_tilt:
    ID: 21
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  turret_pinch:
    ID: 22
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 200
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
